import { AnalysisResult } from '../types';

export const FALLBACK_DEMO_ANALYSIS: AnalysisResult = {
  analysis_id: "ANL-DEMO-ISRO-01",
  status: "COMPLETED",
  satellite: {
    id: "SAT-ISRO-01",
    name: "Cartosat-3 (ISRO High-Res Imaging)",
    altitude_km: 505.0,
    inclination_deg: 97.5,
    period_min: 94.71,
    phase_deg: 14.0,
    raan_deg: 45.0,
    source: "ISRO Telemetry / Ephemeris",
    created_at: new Date().toISOString(),
  },
  objects_analyzed: 8,
  potential_encounters: 8,
  closest_approach_km: 3.82,
  high_risk_count: 2,
  duration_hours: 24.0,
  timestep_seconds: 60.0,
  encounters: [
    {
      id: "ENC-001",
      rank: 1,
      satellite_id: "SAT-ISRO-01",
      satellite_name: "Cartosat-3 (ISRO High-Res Imaging)",
      debris_id: "DEB-1042",
      debris_name: "Cosmos-2251 Collision Fragment (1993-036PX)",
      min_distance_km: 3.82,
      tca_seconds: 14220.5,
      tca_utc: "2026-09-16 14:32:00 UTC",
      relative_velocity_kms: 7.24,
      risk_level: "CRITICAL",
      model: "Simplified Keplerian Propagation",
      trajectory_sample: Array.from({ length: 41 }).map((_, i) => {
        const offsetMin = (i - 20) * 2.25;
        const dist = Math.sqrt(Math.pow(3.82, 2) + Math.pow(offsetMin * 7.24 * 0.45, 2));
        return {
          time_seconds: 14220.5 + offsetMin * 60,
          time_utc_rel: `T${offsetMin < 0 ? '-' : '+'}${Math.abs(Math.round(offsetMin))}m`,
          distance_km: Math.round(dist * 100) / 100,
          sat_pos: [4600 + i * 2, 2200 - i * 3, 4400],
          deb_pos: [4600 + i * 2 + dist, 2200 - i * 3, 4400],
        };
      }),
    },
    {
      id: "ENC-002",
      rank: 2,
      satellite_id: "SAT-ISRO-01",
      satellite_name: "Cartosat-3 (ISRO High-Res Imaging)",
      debris_id: "DEB-0887",
      debris_name: "Fengyun-1C Breakup Debris (1999-025BP)",
      min_distance_km: 11.45,
      tca_seconds: 28940.0,
      tca_utc: "2026-09-16 18:38:20 UTC",
      relative_velocity_kms: 12.85,
      risk_level: "HIGH",
      model: "Simplified Keplerian Propagation",
    },
    {
      id: "ENC-003",
      rank: 3,
      satellite_id: "SAT-ISRO-01",
      satellite_name: "Cartosat-3 (ISRO High-Res Imaging)",
      debris_id: "DEB-2104",
      debris_name: "Iridium-33 Derelict Antenna Fragment",
      min_distance_km: 19.30,
      tca_seconds: 43100.0,
      tca_utc: "2026-09-16 22:34:40 UTC",
      relative_velocity_kms: 9.12,
      risk_level: "MODERATE",
      model: "Simplified Keplerian Propagation",
    },
    {
      id: "ENC-004",
      rank: 4,
      satellite_id: "SAT-ISRO-01",
      satellite_name: "Cartosat-3 (ISRO High-Res Imaging)",
      debris_id: "DEB-0419",
      debris_name: "SL-4 Spent Booster Stage Section",
      min_distance_km: 34.60,
      tca_seconds: 57420.0,
      tca_utc: "2026-09-17 02:30:20 UTC",
      relative_velocity_kms: 14.30,
      risk_level: "MODERATE",
      model: "Simplified Keplerian Propagation",
    },
    {
      id: "ENC-005",
      rank: 5,
      satellite_id: "SAT-ISRO-01",
      satellite_name: "Cartosat-3 (ISRO High-Res Imaging)",
      debris_id: "DEB-0721",
      debris_name: "CZ-4C Debris Shard (2018-088J)",
      min_distance_km: 78.40,
      tca_seconds: 71800.0,
      tca_utc: "2026-09-17 06:30:00 UTC",
      relative_velocity_kms: 11.75,
      risk_level: "LOW",
      model: "Simplified Keplerian Propagation",
    },
  ],
  model_label: "SIMPLIFIED KEPLERIAN MODEL · APPROXIMATE RESULTS",
  disclaimer: "APPROXIMATE SCREENING — Simplified Keplerian propagation. Not intended for operational collision avoidance.",
  unmodeled_effects: [
    "Atmospheric drag (orbital decay for Low Earth Orbit below 600km)",
    "Earth geopotential J2 and higher-order tesseral/sectorial harmonics",
    "Solar Radiation Pressure (SRP) perturbation on high area-to-mass debris",
    "Third-body gravitational perturbations (Lunar and Solar gravitation)",
    "Active satellite collision avoidance maneuvers or thruster firings",
    "Conjunction Assessment Covariance matrices and tracking positional uncertainties",
  ],
  created_at: new Date().toISOString(),
};
