import React from 'react';
import { X, ShieldAlert, CheckCircle2 } from 'lucide-react';

interface LimitationsModalProps {
  onClose: () => void;
}

export const LimitationsModal: React.FC<LimitationsModalProps> = ({ onClose }) => {
  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(15, 23, 42, 0.6)',
        backdropFilter: 'blur(4px)',
        zIndex: 100,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px',
      }}
      onClick={onClose}
    >
      <div
        className="analytical-panel"
        style={{
          width: '100%',
          maxWidth: '680px',
          padding: '28px',
          maxHeight: '90vh',
          overflowY: 'auto',
          position: 'relative',
          backgroundColor: '#FFFFFF',
          border: '1px solid #E2E8F0',
          boxShadow: '0 20px 40px rgba(0, 0, 0, 0.15)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div
              style={{
                width: '40px',
                height: '40px',
                borderRadius: '8px',
                backgroundColor: 'rgba(234, 88, 12, 0.1)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#EA580C',
              }}
            >
              <ShieldAlert size={22} />
            </div>
            <div>
              <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#0F172A' }}>
                Astrodynamic Assumptions & Limitations
              </h2>
              <p style={{ fontSize: '0.8rem', color: '#64748B' }}>
                Technical Specification · Department of Space — ISRO
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            style={{
              background: '#F1F5F9',
              border: '1px solid #E2E8F0',
              borderRadius: '6px',
              padding: '6px',
              color: '#475569',
              cursor: 'pointer',
            }}
          >
            <X size={18} />
          </button>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '18px', fontSize: '0.88rem', lineHeight: '1.6' }}>
          <div
            style={{
              background: '#FEF2F2',
              border: '1px solid #FCA5A5',
              borderRadius: '8px',
              padding: '14px',
              color: '#991B1B',
            }}
          >
            <strong>Operational Advisory:</strong> Results generated by VYOMA represent approximate geometric
            proximity screenings. This platform is a preliminary triage tool, not an operational
            flight-safety system for scheduling real thruster collision avoidance maneuvers (CAM).
          </div>

          <div>
            <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#EA580C', marginBottom: '8px' }}>
              Modeled Physics
            </h3>
            <ul style={{ listStyle: 'none', padding: 0, display: 'flex', flexDirection: 'column', gap: '8px' }}>
              {[
                "Point-mass two-body Keplerian circular mechanics (mu = 398600.4418 km³/s²)",
                "Spherical Earth geocentric radius (R = 6378.137 km)",
                "Analytical 3D orbital plane coordinate transformation (inclination i, RAAN Ω, argument of latitude θ)",
                "Vectorized pairwise Euclidean separation calculation with sub-step parabolic refinement",
                "Relative conjunction velocity vector magnitude at Time of Closest Approach (TCA)"
              ].map((item, i) => (
                <li key={i} style={{ display: 'flex', alignItems: 'center', gap: '8px', color: '#334155' }}>
                  <CheckCircle2 size={16} color="#16A34A" style={{ flexShrink: 0 }} />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#C2410C', marginBottom: '8px' }}>
              Unmodeled Perturbations & Effects
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
              {[
                { title: "Atmospheric Drag", desc: "Causes in-track secular decay for orbits below 600 km" },
                { title: "J2 Geopotential", desc: "Precession of RAAN and apsidal drift from Earth oblateness" },
                { title: "Solar Radiation Pressure", desc: "Area-to-mass perturbations on lightweight debris fragments" },
                { title: "Third-Body Gravitation", desc: "Lunar and Solar tidal gravitational field effects" },
                { title: "Tracking Covariance", desc: "Positional uncertainty ellipsoids and formal B-plane probability" },
                { title: "Spacecraft Maneuvers", desc: "Delta-V station-keeping or orbit-raising burns" }
              ].map((item, i) => (
                <div
                  key={i}
                  style={{
                    background: '#F8FAFC',
                    border: '1px solid #E2E8F0',
                    borderRadius: '6px',
                    padding: '12px',
                  }}
                >
                  <div style={{ fontWeight: 700, color: '#0F172A', fontSize: '0.82rem' }}>{item.title}</div>
                  <div style={{ color: '#64748B', fontSize: '0.75rem', marginTop: '2px' }}>{item.desc}</div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '10px' }}>
            <button
              onClick={onClose}
              className="liquid-button liquid-button-primary"
              style={{ padding: '8px 22px', borderRadius: '6px', fontSize: '0.85rem' }}
            >
              Acknowledge & Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
